version: '3.7'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null

  taskpi:
    image: tusker/api 
    ports:
      - 8000:8000
    environment:
      ENV: "production"
      MONGO_URL: mongodb://mongo
    build:
      context: api
      dockerfile: Dockerfile
    depends_on:
      - mongo

  executor:
    image: tusker/executor
    environment:
      ENV: "production"
      MONGO_URL: mongodb://mongo
    build:
      context: executor
      dockerfile: Dockerfile
    depends_on:
      - mongo
      
  admin:
    image: tusker/admin
    ports:
      - 80:80
    environment:
      API_URL: "http://localhost:8000"
    build:
      context: admin
      dockerfile: Dockerfile